### PR TITLE
BUILD-261: create outside of git control release.yaml to push to repository release page for dev preview install

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan

### CODE REVIEW

**Comment by coreydaley** [comment]
How about something like this in `hack/generate-release-yaml.sh`?
```
#!/bin/bash

FILES=(
"00-namespace.yaml"
"0000_10_projectedresource.crd.yaml"
"01-service-account.yaml"
"02-cluster-role.yaml"
"03-cluster-role-binding.yaml"
"csi-hostpath-driverinfo.yaml"
"csi-hostpath-plugin.yaml"
)

rm -f release.yaml

for FILE in ${FILES[@]}
do

	echo -e "\n---\n" >> release.yaml
	cat deploy/${FILE} >> release.yaml

done
```

Then `make generate-release-yaml` can just be:
`./hack/generate-release-yaml`

**Comment by gabemontero** [comment]
> How about something like this in `hack/generate-release-yaml.sh`?
> 
> ```
> #!/bin/bash
> 
> FILES=(
> "00-namespace.yaml"
> "0000_10_projectedresource.crd.yaml"
> "01-service-account.yaml"
> "02-cluster-role.yaml"
> "03-cluster-role-binding.yaml"
> "csi-hostpath-driverinfo.yaml"
> "csi-hostpath-plugin.yaml"
> )
> 
> rm -f release.yaml
> 
> for FILE in ${FILES[@]}
> do
> 
> 	echo -e "\n---\n" >> release.yaml
> 	cat deploy/${FILE} >> release.yaml
> 
> done
> ```
> 
> Then `make generate-release-yaml` can just be:
> `./hack/generate-release-yaml.sh`

sure I can mess with it next time I circle back to this - thanks

**Comment by gabemontero** [comment]
changes pushed @coreydaley PTAL

given @adambkaplan busy state wrt kubecon, going to 

/unassign @adambkaplan 

and 

/assign @adambkaplan 

if need be we can iterate on this more once Adam actually tries running `make generate-release-yaml` and uploading the content to the repository's release page

**Comment by gabemontero** [comment]
duh :-)

/unassign @adambkaplan 
/assign @coreydaley

**Comment by coreydaley** [comment]
assuming that the new hack/<file>.sh is executable.
/lgtm

**Comment by gabemontero** [comment]
> assuming that the new hack/.sh is executable.
> /lgtm

thanks, and yes, it is:

```
gmontero ~/go/src/github.com/openshift/csi-driver-projected-resource  (gen-rel-yaml)$ ls -la hack
total 24
drwxrwxr-x.  2 gmontero gmontero 4096 May  4 10:49 .
drwxrwxr-x. 12 gmontero gmontero 4096 May  4 10:41 ..
-rw-rw-r--.  1 gmontero gmontero   76 Sep  4  2020 boilerplate.go.txt
-rwxrwxr-x.  1 gmontero gmontero  399 May  4 10:49 generate-release-yaml.sh
-rwxrwxr-x.  1 gmontero gmontero  390 Sep  4  2020 update-crd.sh
-rwxrwxr-x.  1 gmontero gmontero  380 Sep  4  2020 update-generated.sh
gmontero ~/go/src/github.com/openshift/csi-driver-projected-resource  (gen-rel-yaml)$ 
```

**Comment by coreydaley** [comment]
> > assuming that the new hack/.sh is executable.
> > /lgtm
> 
> thanks, and yes, it is:
> 
> ```
> gmontero ~/go/src/github.com/openshift/csi-driver-projected-resource  (gen-rel-yaml)$ ls -la hack
> total 24
> drwxrwxr-x.  2 gmontero gmontero 4096 May  4 10:49 .
> drwxrwxr-x. 12 gmontero gmontero 4096 May  4 10:41 ..
> -rw-rw-r--.  1 gmontero gmontero   76 Sep  4  2020 boilerplate.go.txt
> -rwxrwxr-x.  1 gmontero gmontero  399 May  4 10:49 generate-release-yaml.sh
> -rwxrwxr-x.  1 gmontero gmontero  390 Sep  4  2020 update-crd.sh
> -rwxrwxr-x.  1 gmontero gmontero  380 Sep  4  2020 update-generated.sh
> gmontero ~/go/src/github.com/openshift/csi-driver-projected-resource  (gen-rel-yaml)$ 
> ```

Thanks.
I didn't see a way to tell if it was on github

**Pull request merged**
